#Defaults - https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec


AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - '.git/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

#
## rubocop-performance
#Performance/Size:
#  Exclude:
#    #- lib/example.rb
#
#Rails/FindBy:
#  Exclude:
#    #- lib/example.rb